### ISSUE TITLE
Website has no background

### ISSUE THREAD

**Issue by laurasalisbury** [laurasalisbury/first-website#1]
I'm unsure about how to change the background colour on my new website.

@hellachella

**Comment by hellachella** [comment]
Link a css file, put in:

```
body {
    background-color: (your colour);
}
```

🧐

**Comment by laurasalisbury** [comment]
To clarify, I don't have to fix this for the assignment, right? I just made up an issue for my little website.

**Comment by hellachella** [comment]
No lol!
